name: angular deploy
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 查看当前所在分支
        run: |
          git branch
          git checkout -b gh-pages
          git branch

      # 安装依赖
      - name: Install Dependencies
        # if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          yarn

      # 构建
      - name: Build
        run: |
          npm run docs

      # 部署
      - name: 部署
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "build"
          git push
